// <auto-generated />
namespace DLH_EF_dataconnection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeAnsewer_SurveyToAnswer_Statistic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeAnsewer_SurveyToAnswer_Statistic));
        
        string IMigrationMetadata.Id
        {
            get { return "201705251347032_changeAnsewer_SurveyToAnswer_Statistic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
