// <auto-generated />
namespace DLH_EF_dataconnection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class setUserKey1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setUserKey1));
        
        string IMigrationMetadata.Id
        {
            get { return "201706210247562_setUserKey1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
