// <auto-generated />
namespace DLH_EF_dataconnection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170620_Primary_keys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170620_Primary_keys));
        
        string IMigrationMetadata.Id
        {
            get { return "201706200536129_20170620_Primary_keys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
