// <auto-generated />
namespace DLH_EF_dataconnection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixUserStatisticrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixUserStatisticrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "202007091011227_Fix User-Statistic relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
